### ISSUE TITLE
Commit cf41ccee35327c1b6765433a11cc58cf375b9f16 seems to break buildjob

### ISSUE THREAD

**Issue by stickybyte** [Kurento/libsrtp#1]
The Commit cf41ccee35327c1b6765433a11cc58cf375b9f16 is a couple of days old and it looks like, that this is going to break the manual compile job started by: 
compile_project.py --base_url https://github.com/Kurento compile

The return code is 1 with the following error message:

> [buildpkg::compile_project] (gst-plugins-bad) Project dependency: 'libsrtp', check Debian info
> [buildpkg::compile_project] (gst-plugins-bad) Run 'git ls-remote' (https://github.com/Kurento/libsrtp)
> [buildpkg::compile_project] (gst-plugins-bad) Project dependency 'libsrtp' with no specific version or commit, use Git HEAD: cf41ccee35327c1b6765433a11cc58cf375b9f16
> [buildpkg::compile_project] (gst-plugins-bad) Run 'svn cat' (https://github.com/Kurento/libsrtp/trunk/debian/control)
> [buildpkg::check_dependency_installed] Dependency: '{'commit': 'cf41ccee35327c1b6765433a11cc58cf375b9f16', 'version': None, 'name': 'libsrtp'}'
> [buildpkg::check_deb_dependency_installed] Check Debian dependency installed: libsrtp-dev
> [buildpkg::check_deb_dependency_installed] Dependency 'libsrtp-dev' is not installable via `apt-get`
> [buildpkg::check_deb_dependency_installed] Check Debian dependency installed: libsrtp1
> [buildpkg::check_deb_dependency_installed] Dependency 'libsrtp1' is not installable via `apt-get`
> [buildpkg::check_deb_dependency_installed] Check Debian dependency installed: libsrtp1-dbg
> [buildpkg::check_deb_dependency_installed] Dependency 'libsrtp1-dbg' is not installable via `apt-get`
> [buildpkg::check_deb_dependency_installed] Check Debian dependency installed: srtp-docs
> [buildpkg::get_version_to_install] Found complying version: None
> [buildpkg::check_deb_dependency_installed] Dependency 'srtp-docs' is not installed yet
> [buildpkg::check_deb_dependency_installed] Check Debian dependency installed: srtp-utils
> [buildpkg::get_version_to_install] Found complying version: None
> [buildpkg::check_deb_dependency_installed] Dependency 'srtp-utils' is not installed yet
> [buildpkg::compile_project] (gst-plugins-bad) Build dependency 'libsrtp' is not installed, download and build it
> [buildpkg::clone_repo] Update repo: libsrtp
> fatal: reference is not a tree: cf41ccee35327c1b6765433a11cc58cf375b9f16
> [buildpkg::compile_project] (gst-plugins-bad) ERROR: Checking out the commit 'cf41ccee35327c1b6765433a11cc58cf375b9f16' for build dependency 'libsrtp'
> The command '/bin/sh -c cd kurento-media-server && compile_project.py --base_url https://github.com/Kurento compile' returned a non-zero code: 1

**Comment by j1elo** [comment]
Not an issue with new simpler build script (kurento-buildpackage)
